### ISSUE TITLE
resource `dnacenter_building` inconsistent state handling

### ISSUE THREAD

**Issue by mschedrin** [cisco-en-programmability/terraform-provider-dnacenter#197]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Terraform suggests changing `dnacenter_building` resource every time apply command is used. Based on my log analysis the issue is caused by wrong parsing of DNAC response when refreshing state of `dnacenter_building`. 
Terraform output:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # dnacenter_building.this["Global/MINIHF/OSL/garasje"] will be updated in-place
  ~ resource "dnacenter_building" "this" {
        id   = "name:=Global/MINIHF/OSL/garasje\\site_id:=5de8f601-f79d-42d5-bd48-a37b502fff3e"
        # (1 unchanged attribute hidden)

      ~ parameters {
            # (1 unchanged attribute hidden)

          ~ site {
              ~ building {
                    name        = "garasje"
                  ~ parent_name = "Global" -> "Global/MINIHF/OSL"
                    # (3 unchanged attributes hidden)
                }
            }
        }
    }

  # dnacenter_building.this["Global/MINIHF/OSL/hovedbygg"] will be updated in-place
  ~ resource "dnacenter_building" "this" {
        id   = "name:=Global/MINIHF/OSL/hovedbygg\\site_id:=5749c56b-067a-43b2-857e-8035c06f4062"
        # (1 unchanged attribute hidden)

      ~ parameters {
            # (1 unchanged attribute hidden)

          ~ site {
              ~ building {
                    name        = "hovedbygg"
                  ~ parent_name = "Global" -> "Global/MINIHF/OSL"
                    # (3 unchanged attributes hidden)
                }
            }
        }
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

Terraform state:
```
> terraform state show dnacenter_building.this[\"Global/MINIHF/OSL/garasje\"]
# dnacenter_building.this["Global/MINIHF/OSL/garasje"]:
resource "dnacenter_building" "this" {
    id   = "name:=Global/MINIHF/OSL/garasje\\site_id:=5de8f601-f79d-42d5-bd48-a37b502fff3e"
    item = [
        {
            additional_info     = [
                {
                    attributes = [
                        {
                            address              = "****, Norway"
                            addressinheritedfrom = "5de8f601-f79d-42d5-bd48-a37b502fff3e"
                            country              = "Kazakhstan"
                            floorindex           = ""
                            height               = ""
                            latitude             = "50"
                            length               = ""
                            longitude            = "50"
                            offsetx              = ""
                            offsety              = ""
                            rfmodel              = ""
                            type                 = "building"
                            width                = ""
                        },
                    ]
                    name_space = "Location"
                },
            ]
            id                  = "5de8f601-f79d-42d5-bd48-a37b502fff3e"
            instance_tenant_id  = "62fe613eaa85d640eb70561e"
            name                = "garasje"
            parent_id           = "c13277f8-f4a3-4dbc-8a41-3b674a6c105d"
            site_hierarchy      = "457bfa63-693b-4979-a7fa-2457422cb1a2/edf0263f-e1c9-4c0e-902a-659aa3feb555/c13277f8-f4a3-4dbc-8a41-3b674a6c105d/5de8f601-f79d-42d5-bd48-a37b502fff3e"
            site_name_hierarchy = "Global/MINIHF/OSL/garasje"
        },
    ]

    parameters {
        type = "building"

        site {
            building {
                address     = "****, Norway"
                latitude    = 50
                longitude   = 50
                name        = "garasje"
                parent_name = "Global"
            }
        }
    }
}

```
Relevant part of terraform log demonstrating that DNAC API returns correct site_name_hierarchy:
```
2023-08-28T18:21:19.274+0200 [INFO]  provider.terraform-provider-dnacenter_v1.1.12-beta: 2023/08/28 18:21:19 [DEBUG] Read SiteNameHierarchy => Global/MINIHF/OSL/garasje: timestamp=2023-08-28T18:21:19.274+0200
2023-08-28T18:21:19.274+0200 [INFO]  provider.terraform-provider-dnacenter_v1.1.12-beta: 2023/08/28 18:21:19 [DEBUG] Read name => Global/MINIHF/OSL/garasje: timestamp=2023-08-28T18:21:19.274+0200
2023-08-28T18:21:19.274+0200 [INFO]  provider.terraform-provider-dnacenter_v1.1.12-beta: 2023/08/28 18:21:19 [DEBUG] Read site =>: timestamp=2023-08-28T18:21:19.274+0200
2023-08-28T18:21:19.402+0200 [INFO]  provider.terraform-provider-dnacenter_v1.1.12-beta: 2023/08/28 18:21:19 [DEBUG] [RESTY] 
==============================================================================
~~~ REQUEST ~~~
GET  /dna/intent/api/v1/site?name=Global%2FMINIHF%2FOSL%2Fgarasje  HTTP/1.1
HOST   : ****
HEADERS:
	Accept: application/json
	Content-Type: application/json
	User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
	X-Auth-Token: ***
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 200 OK
PROTO        : HTTP/1.1
RECEIVED AT  : 2023-08-28T18:21:19.402002281+02:00
TIME DURATION: 127.788408ms
HEADERS      :
	Bapiexecutionid: 1b5cc89e-dc24-4584-8469-b79cfd4c0374
	Cache-Control: no-store
	Connection: keep-alive
	Content-Length: 780
	Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data:
	Content-Type: application/json
	Date: Mon, 28 Aug 2023 16:20:52 GMT
	Pragma: no-cache
	Server: webserver
	Strict-Transport-Security: max-age=31536000; includeSubDomains
	Via: api-gateway
	X-Content-Type-Options: nosniff
	X-Frame-Options: SAMEORIGIN
	X-Request-Id: c04a8c51b44243932bb6c68ab5a3660a
	X-Xss-Protection: 1
BODY         :
{
   "response": [
      {
         "parentId": "c13277f8-f4a3-4dbc-8a41-3b674a6c105d",
         "additionalInfo": [
            {
               "nameSpace": "Location",
               "attributes": {
                  "country": "Kazakhstan",
                  "address": "****, Norway",
                  "latitude": "50",
                  "addressInheritedFrom": "5de8f601-f79d-42d5-bd48-a37b502fff3e",
                  "type": "building",
                  "longitude": "50"
               }
            }
         ],
         "name": "garasje",
         "instanceTenantId": "62fe613eaa85d640eb70561e",
         "id": "5de8f601-f79d-42d5-bd48-a37b502fff3e",
         "siteHierarchy": "457bfa63-693b-4979-a7fa-2457422cb1a2/edf0263f-e1c9-4c0e-902a-659aa3feb555/c13277f8-f4a3-4dbc-8a41-3b674a6c105d/5de8f601-f79d-42d5-bd48-a37b502fff3e",
         "siteNameHierarchy": "Global/MINIHF/OSL/garasje"
      }
   ]
}
==============================================================================: timestamp=2023-08-28T18:21:19.402+0200
2023-08-28T18:21:19.402+0200 [INFO]  provider.terraform-provider-dnacenter_v1.1.12-beta: 2023/08/28 18:21:19 [DEBUG] response flatten sent => [{"additional_info":[{"attributes":[{"address":"****, Norway","addressinheritedfrom":"5de8f601-f79d-42d5-bd48-a37b502fff3e","country":"Kazakhstan","floorindex":"","height":"","latitude":"50","length":"","longitude":"50","offsetx":"","offsety":"","rfmodel":"","type":"building","width":""}],"name_space":"Location"}],"id":"5de8f601-f79d-42d5-bd48-a37b502fff3e","instance_tenant_id":"62fe613eaa85d640eb70561e","name":"garasje","parent_id":"c13277f8-f4a3-4dbc-8a41-3b674a6c105d","site_hierarchy":"457bfa63-693b-4979-a7fa-2457422cb1a2/edf0263f-e1c9-4c0e-902a-659aa3feb555/c13277f8-f4a3-4dbc-8a41-3b674a6c105d/5de8f601-f79d-42d5-bd48-a37b502fff3e","site_name_hierarchy":"Global/MINIHF/OSL/garasje"}]: timestamp=2023-08-28T18:21:19.402+0200
2023-08-28T18:21:19.412+0200 [WARN]  Provider "registry.terraform.io/cisco-en-programmability/dnacenter" produced an invalid plan for dnacenter_building.this["Global/MINIHF/OSL/garasje"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .parameters[0].site_id: planned value cty.StringVal("") for a non-computed attribute

```

**Expected behavior**
Provider refreshes the state correctly and does not suggest updating resources when it is not necessary.

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.3-70194
* Terraform version: 1.5.0
* Cisco DNA Center provider version: 1.1.12-beta
* OS Version: Ubuntu 20.04

**Comment by DbarrantesE** [comment]
Hi @mschedrin, I will be reviewing the issue and will let you know.

**Comment by mschedrin** [comment]
@DbarrantesE have you had time to look at this issue?

**Comment by DbarrantesE** [comment]
Hello @mschedrin, between today and tomorrow, we will be uploading an update, so please let us know if the issue has been resolved or if you have noticed anything else

**Comment by DbarrantesE** [comment]
Hi @mschedrin , given the debugs, the identified issues have been fixed. Please try running tests to see if there's anything else in the API that we need to adjust in our code.

**Comment by mschedrin** [comment]
I cannot unfortunately test it because my code does not work with 1.1.13 - 1.1.14 versions due to #204.

**Comment by fmunozmiranda** [comment]
Hi @mschedrin please try it with new version.

**Comment by mschedrin** [comment]
Still cannot test this without doing significant changes to our terraform module, this time due to https://github.com/cisco-en-programmability/terraform-provider-dnacenter/issues/198#issuecomment-1713622261
